name: Jared Dyreson
description: Fullstack Developer 
avatar: https://avatars1.githubusercontent.com/u/13741896?s=460&v=4
title: One stop shop

footer-links:
  dribbble:
  github: JaredDyreson 
  linkedin: jared-dyreson-aa5b67189
  stackoverflow: users/11695624/jared-dyreson 
url: https://jareddyreson.github.io
baseurl: ""
permalink: /:title/
version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
defaults:
  -
    scope:
      path:         ""
      type:         "blog"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "blog"
    href:           "/blog"
  - name:	    "something"
    href:	    "/something"
collections:
  portfolio:
    output: true
    permalinlk: /_portfolio/:path/
